### ISSUE TITLE
Bundle node runtime into workflow?

### ISSUE THREAD

**Issue by florianschmidt1994** [kiliankoe/alfred_dvb#10]
Should we think about bundling a node runtime into the workflow? I guess something like an installer would not be feasable?
How about something like https://github.com/jaredallard/nexe?

**Comment by kiliankoe** [comment]
Just ran into the problem of recommending this workflow to someone else and then more or less forcing them to install node to get it working, so this might not be such a bad idea^^ Will then also omit the need of the hardcoded system path in the shebang.

**Comment by kiliankoe** [comment]
Nexe also looks kinda cool 😮

**Comment by kiliankoe** [comment]
The workflow now includes a go binary, no need for an outside runtime anymore.
