### ISSUE TITLE
Alfred Delay

### ISSUE THREAD

**Issue by kiliankoe** [kiliankoe/alfred_dvb#14]
Just stumbled across [this](https://www.alfredapp.com/help/workflows/utilities/delay/) thanks to @BenchR267. 

Might be a great solution for the notification. I'd love to be able to remove the odd dependency on the swift notification scheduler altogether.

**Comment by kiliankoe** [comment]
✔️ with goalfred and custom vars

**Comment by BenchR267** [comment]
\o/
