### ISSUE TITLE
Not possible to search

### ISSUE THREAD

**Issue by sn3ek** [kiliankoe/alfred_dvb#9]
With the update coming with 0.4.0 i am not able to search any station. When I start typing, the dvb search has stopped working and i get the google search prompted in alfred. 
<img width="630" alt="bildschirmfoto 2016-08-25 um 10 45 10" src="https://cloud.githubusercontent.com/assets/238300/17962415/08a9a8a6-6ab1-11e6-9b33-cb22d1d7cda0.png">

**Comment by kiliankoe** [comment]
O.o

That shouldn't happen. Can you open the Alfred settings to the workflow and click on the bug icon to enable debug mode. Hopefully that should output something when the workflow fails.

**Comment by sn3ek** [comment]
An unexpected token was found:

   Starting debug for 'dvb'

```
[2016-08-25 12:41:27][ERROR: input.scriptfilter] Code 1: ~/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.75E50087-3F7D-491C-98E5-    5F17E2C90CBC/index.js:24
function monitor(stop, timeOffset = 0, numResults = 6) {
                              ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by kiliankoe** [comment]
`Unexpected token =` makes it sound like you might have a node version that doesn't support default function params?

Unfortunately I don't know when that feature was introduced. I'm running node v6.4.0. Can you maybe see if there are updates available?

Typical scripting language problems I guess 😅

**Comment by kiliankoe** [comment]
Or it might just be better to patch that away as well...

**Comment by kiliankoe** [comment]
Just uploaded 0.4.1 to work around this. Hopefully that works.

**Comment by florianschmidt1994** [comment]
Default values for arguments got introduced in node >= v6 (AFAIK). Had the same problem here yesterday

**Comment by sn3ek** [comment]
Yes I had an quite old version of node installed. But 0.4.1 fixed the issue with the older version 👍.

**Comment by kiliankoe** [comment]
Awesome, good to know 😊
